# Generated by Django 4.2.4 on 2023-09-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=3000, unique=True)),
                ('type', models.CharField(choices=[('1', 'Radio'), ('2', 'Select'), ('3', 'Text')], max_length=12)),
                ('choices', models.TextField(blank=True, help_text="The Choice Field is only used if the question type is 'Radio' or 'select', YOU MUST PROVIDE A COMMA-SEPARTED LIST OF OPTIONS FOR THIS QUESTION", max_length=2000)),
                ('answer', models.TextField(blank=True, max_length=2000)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question', to='main.survey')),
            ],
        ),
    ]
