# Generated by Django 4.2.4 on 2023-09-05 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_question_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='participant',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
