# Generated by Django 4.2.4 on 2023-09-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_question_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='Survey_Model',
        ),
    ]
