# Generated by Django 4.2.4 on 2023-09-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_question_answer_remove_question_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participant', to='main.survey_model'),
        ),
    ]
