# Generated by Django 4.2.4 on 2023-09-08 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_participant_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant',
            field=models.OneToOneField(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participant', to='main.survey_model'),
        ),
    ]
